### ISSUE TITLE
[Feature-Request]: getter for memoized keys

### ISSUE THREAD

**Issue by krsinghshubham** [freshworks/memoize_until#10]
There is a use case where i don't want to update the expiry time if the key is not available in the store. Instead i want to take certain action based on whether the key is already memoized or not.
Currently it will save and reset the key if it not available.

Detailed use case:
i want to restrict a lets say redis key to be set by max of a duration (lets say 1 hour), 
i can do ` MemoizeUntil.hour(:remember_action) {  EXISTS redis_key }`
i will have to put restriction on redis to not set that key for more than one hour (first set and then set expiry)

instead i directly or somehow want to set a flag like `MemoizeUntil.hour(:remember_action) { true }` as a one time event and then let the app process the code on wether something like `MemoizeUntil.memoized?(:remember_action) `is true or not .

Possible solution:
expose a new public function in `lib/memoize_until/store.rb `like:
```
def memoized?(key)
  now = Time.now.public_send(_kind)
  value = get(key, now)
  !value.nil?
end
```

**Comment by ritikesh** [comment]
This sounds more like a boot-time configuration than a run-time configuration to me.
> instead i directly or somehow want to set a flag like MemoizeUntil.hour(:remember_action) { true } as a one time event

However, I remember coming across use-cases where we'd want to keep calling the block until it returns a valid value. Not sure if that's what you're looking for, as it could actually end up being a rather expensive usage unless used properly.
